### PR TITLE
Fixed text that links to HPO

### PR DESCRIPTION
**Pull request by nlharris**
The text on https://monarchinitiative.org/phenomics-first linking to HPO said "The The Phenomics First Resource"; changed it to "The Human Phenotype Ontology".

Made a few other minor edits for clarity and correctness (e.g., Peter likes it to be called "The Phenopacket schema", not "Phenopackets"). The Phenopackets text could use some additional updating, I think, but I didn't attempt to do that.

I also noticed that there's a "Coming Soon" note lower down on the page under Phenopackets, but Phenopackets are covered higher on the page.

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Is this still relevant? Maybe Glass pulled it into one of the other PRs they had open? Need to run `yarn lint` to fix test. Or possibly can format right from `.dev` (press `.` on this page) with the default VS Code format document function.

**Comment by nlharris** [comment]
I'm not sure, but https://monarchinitiative.org/phenomics-first still has the old unfixed content (search for "The the").

**Review by glass-ships — APPROVED** [review]
looks good! sorry it took me a bit to get around to this

**Comment by nlharris** [comment]
How long does it take for the fixes to propagate to the live site?

**Comment by glass-ships** [comment]
That currently requires a manual deployment of the new images to Google Cloud - unfortunately @kevinschaper is the most familiar with that process and is away on vacation until next week, but I plan to meet with him to document that process, so we'll look to getting the live site updated at that time.

**Pull request merged**
