### PR TITLE
Update schema, fix docs, and implement new HistoPheno endpoint

### PR DESCRIPTION
**Pull request by glass-ships**

### CODE REVIEW

**Comment by glass-ships** [comment]
Accessibility test probably still failing, but that's not to do with this PR

**Comment by glass-ships** [comment]
Lint test failing because LinkML gen-typescript generates an empty interface for `MetaObject`:

```
> yarn test:lint
yarn run v1.22.19
warning package.json: No license field
$ vue-cli-service lint --no-fix && prettier --ignore-path .prettierignore --check "**/*.{scss,js,ts,json,vue,svg,yaml}" --no-error-on-unmatched-pattern

/mnt/dev/dev/TISLab/monarch-api/frontend/src/api/model.ts
  113:18  error  An empty interface is equivalent to `{}`  @typescript-eslint/no-empty-interface

✖ 1 problem (1 error, 0 warnings)
```

**Comment by glass-ships** [comment]
This accidentally includes the new histopheno endpoint, but I kinda think we should just pull that in anyway since it's working

**Comment by glass-ships** [comment]
Accessibility test still needs to be looked at, but I need to make a new ticket for that anyway.
Otherwise this should be ready.

**Review by kevinschaper — APPROVED** [review]

**Comment by glass-ships** [comment]
just gonna handle this in HistoPheno PR

**Pull request closed without merging**
