### PR TITLE
Incorporate new Monarch API node page endpoints into frontend, other fixes

### PR DESCRIPTION
**Pull request by glass-ships**
frontend (roughly in diff order):

- change node page slug to `/node` instead of `/:category`
- update node/search/etc e2e test content
- add `category_label` to fixture data ahead of api incorporating it
- update node page mock handler 
- remove old node and search fixtures
- remove gene api code! (gene symbol and etc should be included in KG. genome not being used atm.)
- remove unused api code, including old (biolink) endpoints that have been merged into single entity endpoint 
- update model.ts
- make use of category_label instead of category for category display and matching (category-specific UI)
- rename relation to predicate
- rename vars related to useQuery func for clarity
- rename faceting/filtering vars for clarity
- move dropdown select show counts prop to computed within component
- update node page sections to use new endpoints. overview, details, hierarchy, associations count
- remove sections from node page that are not ready yet, i.e. associations, evidence, breadcrumbs. they can always be restored from git history later!

### CODE REVIEW

**Comment by glass-ships** [comment]
Ok, i pulled in @vincerubinetti's vite migration, and everything seems to run without breaking error! 

Unfortunately, among the merge, I think something was broken with the Node and search pages. No matter what you type in, it gives results for Marfan Syndrome, and no matter what put in as an id in the url (for example `localhost:5173/node/MONDO:0012933`) it'll send you to the page for `familial hypercholesterolemia (MONDO:0005439)`

**Comment by vincerubinetti** [comment]
What you're describing just sounds like the api mocking responses. It will return the same static fixture data every time.

Check main.ts if you want to toggle it on or off during prod/test/dev.

**Comment by glass-ships** [comment]
Latest commit includes some rewrites suggested by @vincerubinetti in our scrum today,
finished ironing out some kinks in the node page. 

Couple leftover items:

- SectionAssociations:
  - whole section commented out for now, need to dig a little deeper into association files to really get that working, i might need @kevinschaper 's help on that bit

- SectionTitle: 
  - commented out `originalId` (no equivalent in new Node model)

- SectionDetails
  - commented out `iri` and `modifiers` (no equivalents in new Node model)

**Comment by glass-ships** [comment]
Working on SectionAssociations, AssociationsTable/Summary, and EvidenceViewer. 

Has also required digging into breadcrumbs, AppNodeBadge, AppRelationBadge (made new replacement called AppPredicatebadge), and re-implementing utility methods from `node-associations.ts`

Table and summary render, but don't populate with any meaningful data

**Comment by vincerubinetti** [comment]
Have the typescript array and optional issues been fixed? It seems like maybe so? If so, i think this PR may be at the point where i'll need to step in.

**Comment by glass-ships** [comment]
> Have the typescript array and optional issues been fixed? It seems like maybe so? If so, i think this PR may be at the point where i'll need to step in.

I don't think there's been a linkml release that includes those changes yet, so I've pointed poetry to a branch I made that includes the necessary changes (`linkml = { git = "https://github.com/glass-ships/linkml.git", branch = "develop" }`). You may have to delete your `backend/.venv` and `poetry install` again, but yeah the model generated is (read: should be) correct.

**Review by vincerubinetti — APPROVED** [review]

**Comment by vincerubinetti** [comment]
This is ready to merge from my perspective. Can someone with the knowledge of the backend please resolve the merge conflicts and merge (with the default commit message that will take the bullet point list of changes in the first comment).

**Comment by vincerubinetti** [comment]
~I'll revert to using `category[0]` for this PR instead of `category_label` just for now, since a single value `category` won't be available in the real API yet for some time. And we can add back in the changes here in the backend PR that adds the single value.~

**Comment by glass-ships** [comment]
Some model conflicts now occurring on node views:
- Node missing `category_label`
- ~AssociationCount missing `association_type`~
- SearchResult missing `category_label`

**Review by kevinschaper — APPROVED** [review]

**Pull request merged**
