### PR TITLE
remove spacy dependancy in pyproject.toml

### LINKED ISSUE #809: Spacy git dependency breaks pypi deploy
Our deploys of monarch-py as a library have been failing for a while, it looks like we need to get our spacy dependency pointed at a release version.

```
Using a plaintext file to store credentials

Publishing monarch-py (v1.8.0-rc2) to PyPI
 - Uploading monarch_py-1.8.0rc2-py3-none-any.whl 0%

 - Uploading monarch_py-1.8.0rc2-py3-none-any.whl 100%
HTTP Error 400: Can't have direct dependency: spacy@ git+https://github.com/explosion/spaCy.git@master. See https://packaging.python.org/specifications/core-metadata for more information. | b"<html>\n <head>\n  <title>400 Can't have direct dependency: spacy@ git+https://github.com/explosion/spaCy.git@master. See https://packaging.python.org/specifications/core-metadata for more information.\n \n <body>\n  <h1>400 Can't have direct dependency: spacy@ git+https://github.com/explosion/spaCy.git@master. See https://packaging.python.org/specifications/core-metadata for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nCan&#x27;t have direct dependency: spacy@ git+https://github.com/explosion/spaCy.git@master. See https://packaging.python.org/specifications/core-metadata for more information.\n\n\n \n"
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by madanucd**
### Related issues

- Closes #809 

### Summary

This PR addresses dependency issues with `monarch-py` deployment to PyPI, fixing errors caused by direct dependencies on external URLs for spacy  `en_core_sci_sm` model.

- Utilized pystow to download and cache the en_core_sci_sm model from an S3 URL.

- Implemented automatic unpacking and dynamic directory identification to ensure the model is properly extracted and loaded.

### Checks

- [x] All annotation backend tests were checked and successfully passed.
- [x] Completed testing of the API development environment to ensure proper integration.

### CODE REVIEW

**Comment by ptgolden** [comment]
Hey @madanucd, are there any substantial changes in those last three commits? I think you may not have pulled from `main` before making the PR, which made all changes after 838436e66a1e9df44a9957d91b90d518c9aca4e0 a little wonky (they revert all commits from the last month or so). If there aren't changes that aren't semantically meaningful for this PR/issue, I'll cherry pick 838436e66a1e9df44a9957d91b90d518c9aca4e0 and update `poetry.lock` from its `HEAD` state in `main`.

**Comment by madanucd** [comment]
Hi @ptgolden 

The only updates in this branch are to the following files:

- `backend/src/monarch_py/implementations/spacy/spacy_implementation.py`
- `pyproject.toml`

The `poetry.lock` file was updated due to changes in `pyproject.toml`.

Merging `main` into `issue-809-dependency-update` seems to have flagged multiple files as modified, even though only the files listed above were intentionally updated. This discrepancy might create unnecessary confusion. After reverting the aforementioned merge commit, I did not encounter any build failures or conflicts. That said, I ensured my `main` branch was up to date before creating this branch.

If cherry-picking the relevant commit works better for you, please feel free to proceed. Alternatively, I can create a clean branch and submit a new PR to ensure clarity, deleting this branch and the current PR. Please let me know how.

**Comment by ptgolden** [comment]
Strange- the parent commit of 838436e66a1e9df44a9957d91b90d518c9aca4e0 is 793cd1cc9c6f59eeee957045eb4a34b01087e8b8 from 10/21 (the lock file has diverged since then). I am happy to make a new PR cherry picking 838436e66a1e9df44a9957d91b90d518c9aca4e0 and updating `poetry.lock` from its current state, if that's OK with you.

**Comment by madanucd** [comment]
> Strange- the parent commit of [838436e](https://github.com/monarch-initiative/monarch-app/commit/838436e66a1e9df44a9957d91b90d518c9aca4e0) is [793cd1c](https://github.com/monarch-initiative/monarch-app/commit/793cd1cc9c6f59eeee957045eb4a34b01087e8b8) from 10/21 (the lock file has diverged since then). I am happy to make a new PR cherry picking [838436e](https://github.com/monarch-initiative/monarch-app/commit/838436e66a1e9df44a9957d91b90d518c9aca4e0) and updating `poetry.lock` from its current state, if that's OK with you.

That's fine with me. Thank you!

**Comment by ptgolden** [comment]
New PR in #920 :+1:

**Pull request closed without merging**
