### PR TITLE
Monarch organizational home page changes to highlight foundational products

### LINKED ISSUE #672: Configure redirects from monarchinitiative.org
Let's borrow from the convenience of https://github.com/tis-lab/redirects/blob/main/redirects.yaml to create nginx redirects in our nginx config. 

I'm guessing we'll have a step to translate the yaml into nginx redirect format, and then we'll need to use some kind of include directive to bring that into the nginx config.

### PR DESCRIPTION
**Pull request by kevinschaper**
Not my branch (mostly), but we need a PR for it

### CODE REVIEW

**Comment by amc-corey-cox** [comment]
This should be ready for review now! Please check it out using the link above in the Netlify Deployment preview above.
@monicacecilia & @sagehrke

**Comment by amc-corey-cox** [comment]
@kevinschaper Can you take  a look at this one? I'd like to get your input before I merge. I think it looks pretty good and I believe we have covered most of the UI redevelopment that we were hoping to get to in this phase.

**Comment by kevinschaper** [comment]
Looks good! I want to make a better destination for the KG link on the home page than just search, but I don't think that needs to be in this PR.

**Review by sagehrke — COMMENTED** [review]
Thanks for all your work on this @amc-corey-cox! If this PR was only focused on the homepage, please ignore my other critiques. 

## home page
- No updates for now. This is a great first update to the new website interface. 

## explore page
- We are still missing some aspects of this ticket: https://github.com/monarch-initiative/monarch-app/issues/777
- I am also curious what we think of moving the infographic to the top of the page. 

## team page
- See updates here: https://github.com/monarch-initiative/monarch-app/issues/796

**Pull request merged**
