### PR TITLE
Implement SemanticSimilarity / semsimian (WIP)

### PR DESCRIPTION
**Pull request by glass-ships**
Addresses #192 

- [x] Adds solr/oak implementations to `api.config.solr` for example, to instantiate once on startup and call later
    - this may not be working as i expect yet
- [x] Implements `termset_pairwise_similarity`
- [x] Updates model from changes to `provided_by` and `primary_knowledge_source` in Associations
- [ ] ?

semsimian isn't quite ready for this, but being worked on, related issues: 
- https://github.com/INCATools/ontology-access-kit/issues/619
- https://github.com/INCATools/ontology-access-kit/issues/620

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@glass-ships It looks like this somehow doesn't contain some of the frontend changes we made in the `coming-soon` branch.

E.g. this should still have the dropdowns to select which mode you want, and it should say coming soon if you select set-to-taxon:

Screenshot 2023-08-22 at 5 13 16 PM


I see that you merged in that branch, but somehow the changes to `src/pages/explore/TabPhenotypeExplorer.vue` got reverted.

Spot checking, just from memory, it looks like all the other coming-soon and about section changes we made have stayed. But I would take another very close look through the code to make sure the merge kept everything.

**Comment by kevinschaper** [comment]
Something definitely went wrong when I merged main, I don't see a merge commit for that, and unfortunately it turned into a step by step rebase

**Comment by vincerubinetti** [comment]
Actually, let me fix the issues in `TabPhenotypeExplorer.vue`. The problem is there's some changes we want to keep from this semsim pr (like changing the search box placeholder text, and changing the result ring score calcs), and some things we want to keep from the coming-soon pr (alert box).

Please someone else help my by spot checking against coming-soon and the about section prs. From my checks, it seems like `TabPhenotypeExplorer.vue` is the only thing with a problem.

**Comment by vincerubinetti** [comment]
Okay, the fix was small and simple. It was just a few things commented out that shouldn't have been. Otherwise, the correct changes were taken from this branch and the coming-soon branch.

**Review by vincerubinetti — APPROVED** [review]

**Review by kevinschaper — APPROVED** [review]

**Pull request merged**
