### PR TITLE
change api root logic

### LINKED ISSUE #284: Add "relative" path to list of API urls?
Since hosting the UI alongside the rest of the v3 stack, I've noticed that all the options in the list below are absolute URLs.

https://github.com/monarch-initiative/monarch-app/blob/f4eb50c6220ee668cd5054f3df1f6e4609afe3e3/frontend/src/api/index.ts#L33-L38

Would it be possible to add an extra option, say "relative", that makes the API URL a relative URL, e.g. `{ relative: "/v3/api" }`?

With that in place, I'd be able to more easily test the UI container since it'll be running from the same host as the API.

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #284 

- rework how api flags are handled. add "relative" mode for arbitrary domain.

### CODE REVIEW

**Review by glass-ships — COMMENTED** [review]
yeah this looks good to me, it's a nice flexible option

**Review by glass-ships — APPROVED** [review]

**Review by falquaddoomi — APPROVED** [review]
Looks good, and it addresses my needs. Thanks!

**Review by kevinschaper — APPROVED** [review]

**Comment by kevinschaper** [comment]
I want to move to relative urls `<host>.mi.org/api/v3` - but we shouldn't commit that change to the api until we have it working on the back end.

**Comment by vincerubinetti** [comment]
Okay so I guess we'll merge for now and change it later. Also, I hope we decided on "next", but it's still "v3" at the moment, so I'll change the fallbacks to that.

**Pull request merged**
