### PR TITLE
Updating Teams Page again

### LINKED ISSUE #74: Create Monarch SAB page

### LINKED ISSUE #489: Update Team Page on UI - summary of all changes
@glass-ships This ticket is a summary of the Team page updates mentioned in the following tickets: 
- [x] https://github.com/monarch-initiative/monarch-app/issues/74
- [x] https://github.com/monarch-initiative/monarch-app/issues/304
- [x] https://github.com/monarch-initiative/monarch-app/issues/399

Please address the previous comments on the above tickets and the new information below. 

Next steps:
- Cross check the list of members in the "MonarchTeam" tab of the **The Monarch Initiative contact list** [not linking here as it is a private document - see Slack message from me with the link] with what is already listed on the website Team page. 
  - Identify who needs to be added or removed 
  - Confirm who needs a new headshot and who is missing a link to their info page on an external site. 
    - Share this list with me in a google sheet on Slack so I can help ping folks. 
- Reminder from the tickets listed above - we are only listing the alumni with their names - no photos or links
- SAB members will be added before the alumni section. Include photos and links. 

Note: it seems reasonable to finish this for the December release. To clean this up for the new year, if we are missing some current member pictures or links, let's still push this out for Dec 14th so we can close these tickets. Anything left over and still needing an update can be made into a new January ticket with specific additional needs addressed.

### PR DESCRIPTION
**Pull request by glass-ships**
Closes #489, #74, #304 and #399 

- [x] still need links, roles, and pics for several members
- [x] could probably use better images for SAB
- [x] may need help removing default profile pictures for alumni (if possible), just turning into a text list or table

### CODE REVIEW

**Comment by glass-ships** [comment]
thanks for looking at the tests @vincerubinetti ! 
also wondering, what would be your recommended approach to the last checkbox in the pinned comment?

**Comment by vincerubinetti** [comment]
I implemented that in that last commit, I just added a `noImage` param to the `AppMember` component.

**Comment by glass-ships** [comment]
oh awesome!! you're the best, thanks man

**Comment by vincerubinetti** [comment]
Still working on fixing the unit test. It doesn't fail for me locally.

**Comment by vincerubinetti** [comment]
Well I really can't figure out right now why unit is failing on gh-actions but not locally. `document` should be defined because the unit tests run in the `jsdom` environment which replicates the browser. So I just added a check for if doc is defined.

Playing around with the package versions, I think it's probably some kind of weird version compatibility bug. So this may be fixed by upgrading all the packages in the future (I want to do this in the next few months as a separate dedicated PR).

**Review by vincerubinetti — APPROVED** [review]

**Comment by sagehrke** [comment]
@glass-ships Minor updates, and then I can approve: 
- Damian Smedley's Role should be updated to **Monarch PI**
- **Remove** Chris Chute's Role (just leave it blank)

All the rest is good! We will follow up in the coming month to chase after any missing content. Thank you!

**Review by sagehrke — APPROVED** [review]

**Pull request merged**
