### PR TITLE
second pass at multi-entity assocations endpoint

### PR DESCRIPTION
**Pull request by glass-ships**
Addresses #270 

no CLI implementation yet, still working out the under-the-hood stuff.

currently just manually testing/checking output with:
```python
from monarch_py.implementations.solr.solr_implementation import SolrImplementation
from monarch_py.utils.utils import to_json
from pprint import pprint

si = SolrImplementation()

results = si.get_multi_entity_associations(
    entity=["MONDO:0012933", "MONDO:0005439"], counterpart_category=["biolink:PhenotypicQuality", "biolink:Disease"]
)
print(len(results))
count = 0
for i in results:
    count += 1
    to_json(i, file=f"test_multi_endpoint_{count}.json")
```

### CODE REVIEW

**Comment by glass-ships** [comment]
is this maybe closer to what you were imagining @oneilsh ?

**Comment by oneilsh** [comment]
@glass-ships yes I think so!

**Comment by oneilsh** [comment]
@glass-ships I was just noticing the if `entity == None: continue` lines; I think if there's not a good match for a requested entity then something should be returned in that vs an entity that doesn't have any associations. Currently it looks like a lack of an entity in the response means it couldn't be found, while an entity without associations would get an entry in the return that is empty right? I wonder if each entity shouldn't have a basic "status" field to indicate if it wasn't found, or maybe the category for the entity should be null or something. I dunno, open to suggestions.

```
entities:
    - id: "MONDO:NOSUCHID":
      name: null
      category: null # like this maybe?
      status: "not found" # or like this?
    - id: "MONDO:113513"
      ...
```

**Comment by glass-ships** [comment]
hey @oneilsh, sorry again for the delay between check-ins. 
how does the most recent commit look? 
I added a bit before the continue statement that may address this concern, for example, running:
```python
results = si.get_multi_entity_associations(
    entity=["MONDO:0012933", "MONDO:0005439", "MANGO:0023456"], 
    counterpart_category=["biolink:PhenotypicQuality", "biolink:Disease"]
)
```

would return this for the last entity ID:
```python
{
    "limit": 20,
    "offset": 0,
    "total": 0,
    "id": "MANGO:0023456",
    "name": "Entity not found",
    "associated_categories": []
}
```

**Comment by oneilsh** [comment]
@glass-ships I like it, thank you! I'm excited, this is going to be a very friendly endpoint (both both humans and AI models :P). In the future we may want to consider different options for sorting results (e.g. by evidence count, or betweenness centrality, or embedding similarity to a given query string, ...), but that can be for another day.

**Review by kevinschaper — APPROVED** [review]
This is awesome, thank you @glass-ships!

**Comment by glass-ships** [comment]
should i add a CLI command before merging this? @kevinschaper / @oneilsh

**Comment by kevinschaper** [comment]
Nah, I think we should just merge it in, but maybe also make an issue to add the cli endpoint.

**Pull request merged**
