### PR TITLE
update Phenomics First page

### LINKED ISSUE #422: Phenomics first page has some empty content boxes
The Phenomics First webpage has empty content boxes. https://monarchinitiative.org/phenomics-first

- [x] The Mondo tile needs to have a paragraph added. Pull content from [here](https://mondo.readthedocs.io/en/latest/). Make sure to include the link to this read the docs site as well. 
- [x] The Phenopackets tile needs to have a paragraph added. Pull content from [here](http://phenopackets.org/). Make sure to include a link to the phenopackets.org site as well. 
- [x] The last box called "The Phenomics First Resource" needs to be deleted. 

Screenshot 2023-10-20 at 1 06 50 PM

### PR DESCRIPTION
**Pull request by glass-ships**
Closes #422

### CODE REVIEW

**Comment by glass-ships** [comment]
@monicacecilia updated page preview can be seen at https://deploy-preview-423--monarch-app.netlify.app/phenomics-first

**Comment by vincerubinetti** [comment]
`target="_blank"` is not needed, the link component does it automatically.

**Comment by glass-ships** [comment]
i'll fix that in the resources page PR

**Comment by vincerubinetti** [comment]
i've also fixed it in #468

**Pull request merged**
