### PR TITLE
Monarch-app - how to page

### LINKED ISSUE #400: Add "How to" page on the Monarch App
Create a page in the Monarch App that details how to use and interpret various functions of the site, including definitions of common terms. This can also be done with the hover-over text info bubbles if that makes more sense.

### LINKED ISSUE #567: Feedback form - Sierra Moxon - Thank you for the lovely new interface! I was searching a...
**Name**
Sierra Moxon

**Email**
smoxon@lbl.gov

**GitHub Username**
@sierra-moxon

**Details**
Page: /feedback
Browser: Chrome 120.0.0.0
Device: Apple Macintosh
OS: Mac OS 10.15.7
Engine: Blink 120.0.0.0

Thank you for the lovely new interface! 

I was searching around for the equivalent of this: https://previous.monarchinitiative.org/analyze/phenotypes in the new UI and couldn't find it.   Maybe this is just a me-problem w/re to "Tools" vs. "Explore" :) 

Kevin pointed me to this: http://monarchinitiative.org/explore#phenotype-explorer.  I didn't figure out that I could enter a disease in the second box, nor that I could request to find diseases because the pulldowns both start with "phenotype" and I couldn't figure out how to ask it to "just show me diseases that have matching phenotypic profiles".  The old UI had a really good user walk-through.  It gave me help up front if I needed it, clearly asked me to define whether I wanted all diseases or one particular disease back,  and had some intermittent feedback about the terms I put in matching the terms it had.  

I guess the third issue (and most important, UI aside), is that I don't get diseases back (using the old UI) when the disease is a "grouping term" for other diseases.  E.g. if I search for all the phenotypes of the two sub-types of Cerebral Palsy, I would expect to get Cerebral Palsy back in the results of diseases that match my phenotypic profile.   Instead I only get some sub types of the disease.  Same for Marfan Syndrome and Ehlers-Danlos.

### LINKED ISSUE #670: User Feedback for How-To
We are gathering some limited user feedback to find out what parts of the Monarch App could use some clarifying information. We are planning to add a How-To section for the website that gives more detailed instructions on how to use the different components of the Monarch App. We're hoping for feedback on specific tasks that users want to complete that it may not be completely clear how to do in the UI.

I have collected the below feedback into a list here:
- [x] Add a section for using Monarch programmatically with API, R, or ChatGPT assistant.
- [x] Fix typo “Genes can be searched by common gene, gene ID, “ —> “common gene name, gene ID, …"
- [x] Move down the clickable HT icon. Make a new section below _“What is Monarch?”_ and its four tiles.
- [x] Gene of interest search results, add Taxon info for clarity.

### PR DESCRIPTION
**Pull request by amc-corey-cox**
### Related issues

- Closes #400

### Summary

- adds a HowTo page that has expanded information on how to use the Monarch tools

### Checks

- [x] All tests have passed (or issues created for failing tests)

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Perhaps the AppTile belongs on the help page.

**Comment by amc-corey-cox** [comment]
@monicacecilia I have finished a few mock-ups of the How-To with some example content and some ideas for how we might want things to look and feel. I'd like to set up a meeting to run through it, capture your thoughts, and start to refine what we're trying to achieve. If you'd like to see it on your own you can check it out at the link below.

https://deploy-preview-597--monarch-app.netlify.app/how-to

I want to warn you this is pretty rough! It will need a fair amount of polish before we deploy it but I think the bones of something we will want should be there. It shouldn't take too much effort to get it finished once we've reviewed what we like or don't want. I'll reach out by e-mail to look at it together or we can do that at our Tuesday meeting.

**Comment by amc-corey-cox** [comment]
closes #670
closes #567
closes #597

**Comment by amc-corey-cox** [comment]
I believe this is ready to go. Please take a look especially at the last couple sections (AI, and about) and tell me if you want any changes. Otherwise, let's merge and get this done!

**Review by glass-ships — APPROVED** [review]
nice work, this looks great!

**Pull request merged**
